### PR TITLE
Development

### PR DESCRIPTION
**Pull request by andrewmeyer**
adds a very simple postfix check that looks at the local host.  we make sure that postfix is running and then check a list of ports.  The ports may optionally be prepended with a bind address.

### CODE REVIEW

**Comment by phil21** [comment]
code looks fine but the filename is named horribly check_pfx makes me think check_prefix first.  

check_postfix likely works a bit better

**Comment by andrewmeyer** [comment]
No I agree, I cut a corner to fix a false negative in the script.  Postfix doesn't run anything called postfix outright so I'll adjust the check to properly find the process and not find the check script

Andrew Meyer
IT Linux Administrator
Sent from my mobile device, please excuse my brevity and typos

On Nov 8, 2017 4:04 PM, Phil Doroff <notifications@github.com> wrote:

code looks fine but the filename is named horribly check_pfx makes me think check_prefix first.

check_postfix likely works a bit better

**Comment by andrewmeyer** [comment]
Phil, can you look again?  file has been renamed and the false-negative removed

**Comment by phil21** [comment]
👍

**Pull request merged**
